name: theodoi_hoctap
description: "Theo doi tien do hoc tap - So lien lac so"
publish_to: 'none'
version: 0.4.5+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.17.2
  uuid: ^4.6.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_image_compress: ^2.5.1
  path_provider: ^2.1.6
  cross_file: ^0.3.5+5
  gal: ^2.3.1
  http: ^1.2.0
  web: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
